name = "weather-withmatt-com"
main = "worker/index.ts"
compatibility_date = "2025-08-08"
compatibility_flags = ["nodejs_compat"]

# Static Assets configuration
[assets]
directory = "build"
binding = "ASSETS"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "weather-withmatt"
database_id = "b505e9ec-b556-4758-9316-2b70b6bad88a"
